### PR TITLE
Toyzero dataset preprocessed

### PR DESCRIPTION
**Pull request by usert5432**
Toyzero dataset that uses preprocessed list of image crops.

### CODE REVIEW

**Review by brettviren — APPROVED** [review]

**Review by YHRen — COMMENTED** [review]
Thank you for the PR, here are my two cents. 
* I think `GenericDataset` is unnecessary. 
* I suggest to inherit from `torch.utils.Dataset` instead. (which requires `__getitem__` and `__add__`. So, less trouble down the road.)
* [optional] I suggest to separate the logic of dataset splitting away from the dataset, and use [`torch.utils.data.random_split`](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#random_split) outside of this scope. Also avoids problems in distributed training.

**Comment by usert5432** [comment]
Hi @YHRen,

Thank you for your comments! May I ask your opinion about the following?
> * I think GenericDataset is unnecessary.
> * I suggest to inherit from torch.utils.Dataset instead. (which requires `__getitem__` and `__add__`. So, less trouble down the road.)

The `pytorch` dependency is very heavy and I did not want to hard depend on it, since it will limit the number of systems where the `toytools` can be run. E.g. I do not have `pytorch` on my laptop, but I can easily test datasets and make plots of cropped regions that they produce with the current setup on my laptop.

However, I realize that my usecase is very special, and maybe it is easier just to depend on `pytorch` from the start. Do you think it is ok to leave datasets as they are, or it is better to inherit them from `torch.utils.Dataset` directly?

**Comment by YHRen** [comment]
> Hi @YHRen,
> 
> Thank you for your comments! May I ask your opinion about the following?
> 
> > * I think GenericDataset is unnecessary.
> > * I suggest to inherit from torch.utils.Dataset instead. (which requires `__getitem__` and `__add__`. So, less trouble down the road.)
> 
> The `pytorch` dependency is very heavy and I did not want to hard depend on it, since it will limit the number of systems where the `toytools` can be run. E.g. I do not have `pytorch` on my laptop, but I can easily test datasets and make plots of cropped regions that they produce with the current setup on my laptop.
> 
> However, I realize that my usecase is very special, and maybe it is easier just to depend on `pytorch` from the start. Do you think it is ok to leave datasets as they are, or it is better to inherit them from `torch.utils.Dataset` directly?

Hi @usert5432  , I misunderstood the purpose of this code. Somehow I thought this pre-processing code will be added into `ls4gan-python`... If this code is in `toytools` (the simulation and data generation), we definitely don't want it to depend on `pytorch`.

**Review by pphuangyi — COMMENTED** [review]
**presimple_toyzero.py line 28:** `reproducible`

**Comment by usert5432** [comment]
> **presimple_toyzero.py line 28:** `reproducible`

Thanks!

**Comment by usert5432** [comment]
> Hi @usert5432 , I misunderstood the purpose of this code. Somehow I thought this pre-processing code will be added into `ls4gan-python`... If this code is in `toytools` (the simulation and data generation), we definitely don't want it to depend on `pytorch`.

Thank you @YHRen!

>     * [optional] I suggest to separate the logic of dataset splitting away from the dataset, and use [`torch.utils.data.random_split`](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#random_split) outside of this scope. Also avoids problems in distributed training.

I will implement it in the later PR, since such a change will affect multiple, yet uncommitted files. I have made an issue https://github.com/LS4GAN/toytools/issues/6#issue-948658169 to track the progress.

**Pull request merged**
